### ISSUE TITLE
Logo design for 3pm

### ISSUE THREAD

**Issue by harunbadilli** [ChrisPara/3pm#18]
I designed a logo for 3pm. Simple and stylish design with a time-like look. I've made the value of time even clearer with the harmony of colors. I wanted to present this logo specifically to you. I'm asking you to accept it.

![1](https://user-images.githubusercontent.com/34319922/40585963-0855d7a2-61c3-11e8-8b25-a754bb837120.png)
![2](https://user-images.githubusercontent.com/34319922/40585964-0880db46-61c3-11e8-9e71-c5c15916bf9b.png)
![3](https://user-images.githubusercontent.com/34319922/40585965-08ab0808-61c3-11e8-8fcc-b9b68bb3fc05.png)

**Comment by scheingraber** [comment]
Is this a bot?

**Comment by scheingraber** [comment]
Thanks in any case 👍  :)

**Comment by harunbadilli** [comment]
this is a logo and  I thank you for what you see fit :)

**Comment by harunbadilli** [comment]
which files do you want me to send
