### ISSUE TITLE
Windows settings/data location

### ISSUE THREAD

**Issue by acicovic** [ChrisPara/3pm#23]
Hi!

Where does 3pm store data/settings in the Windows environment?

Thanks!

**Comment by scheingraber** [comment]
Hi acicovic,

Settings are stored in the folder from where you started the executable, in ".pppm.ini"
Data are stored in %AppData%\project, e.g. C:\Users\acicovic\AppData\Roaming\project

**Comment by acicovic** [comment]
Thanks for the info. Is there currently a way to make the program fully portable? (store all data within the program's folder).

Thanks!

**Comment by scheingraber** [comment]
Hi Alex,

I have added that as an option now in the new version 0.6.9. Look for "Store data in app folder" in the settings. Let me know how it works for you :)

**Comment by acicovic** [comment]
Works well! thanks!
